[package]
name = "better-tactics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.2.2"
env_logger = "0.10.0"
log = "0.4.20"
owlchess = "0.4.0"
sqlite = "0.31.1"
zstd = "0.12.4"
